name: sli_slo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  freezed_annotation: 2.4.1
  sentry: 8.2.0
  built_collection: 5.1.1
  dartx: 1.2.0
  dio: 5.4.3+1
  riverpod: 2.5.1
  logger: 2.3.0
  meta: 1.11.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  freezed: 2.5.2
  test: 1.25.2
